version: '3.8'

services:
  # Main web application
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      # Mount source code for hot reload
      - ./src:/app/src:ro
      - ./docs:/app/docs:ro
      - ./.eleventy.js:/app/.eleventy.js:ro
      # Don't mount node_modules (use container's version)
      - /app/node_modules
    environment:
      - ELEVENTY_ENV=development
      - NODE_ENV=development
    command: npm start
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8080/"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 40s

  # QA Agent system (optional - only start when needed)
  qa:
    build:
      context: ./qa_agents
      dockerfile: Dockerfile.qa
    volumes:
      - ./qa_agents:/app/qa_agents
      - ./.env:/app/.env:ro
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - PYTHONPATH=/app
    depends_on:
      web:
        condition: service_healthy
    profiles:
      - qa  # Only start with: docker-compose --profile qa up
    command: python3 qa_agents/run_responsive_review.py
